### ISSUE TITLE
CSS code not sticking

### ISSUE THREAD

**Issue by jghike** [eduramiba/moodle-theme-uikit#9]
I'm trying to edit the CSS for the login page to show the login and create an account in two different columns, as they are currently in one column. However, any changes I make to the CSS code aren't being applied to the Moodle site, even something as simple as adding an ouuotline to a  text box. Am I missing something?

**Comment by borisvmalysh** [comment]
Hello everybody!
I've got a similar problem:
Trying to customize the look of quiz questions I've found some useful code and tried to paste it through the " Use your own custom CSS/LESS code" box in the visual style manager. I've clicked the "save and use styles" button, got the message saying "Styles saved successfully!". But it hasn't changed anything.
Most likely I'm doing something wrong, but I hope to find a solution here.

<strong>DETAILS:</strong>

Here's waht I'm trying to do:
![quiz layout task](https://cloud.githubusercontent.com/assets/9256159/5719137/8c51a34a-9b26-11e4-8007-114fa5856ede.png)

Here's the code I've found:
.que .info {

float: none;
width: auto;
}

.que .info > div {
margin-left: 10px;
margin-right: 10px;
}

.que .info > div, .que .ablock > div, .que .answer > div {
display: inline;
}

.que .content {
margin: 0 0 0 0;
width: auto;
}


Here's how I pasted it:
![image](https://cloud.githubusercontent.com/assets/9256159/5719201/455d9434-9b27-11e4-9f47-7436bd537c14.png)



This is the button I've pressed:
![image](https://cloud.githubusercontent.com/assets/9256159/5719235/9ce5ee5e-9b27-11e4-99ab-6957566d3072.png)


And this is the message I've got:
![image](https://cloud.githubusercontent.com/assets/9256159/5719240/b6c721c6-9b27-11e4-85b4-ed4b6c136b5e.png)



I would be VERY happy if you could help. Hopefullynot only me, because the theme is awesome and deserves being improved.
BIG THX.

**Comment by eduramiba** [comment]
Hi, if you pasted the code, the customizer might not detect changes to the custom css and ignore it.
A workaround is to make some change to the custom css manually, refresh and then save.
Anyway, I improved the detection of changes to custom css for next version.

Also, keep in mind that if you don't enable auto-refresh, and save without refreshing, custom css changes won't be applied.

The best way to make sure that your css will work is by navigating to the quiz page inside the customizer UI and seeing how your changes affect the site.

**Comment by eduramiba** [comment]
This seems to still not work in latest firefox, since no events are received when the text changes, I reopen it.
